:PROPERTIES:
:ID:       c6fd8ff7-b020-47bf-8d96-ad1cab2294b8
:END:
#+TITLE: What Are the Logical Components of a minimal DRP stack?

* Introduction

The *primary consideration* of DRP as a technical solution is that it is a standard interchange format for Data Subject Requests.

What are the minimal logical components of a DRP stack? What would it take to implement the DRP protocol?

We should be careful when and consider not crafting specific user-flows in to the protocol to allow for the development of a healthy community of Authorized Agents and Privacy Infrastructure Providers, comprehensive and niche. This advice maybe flies in the face of the =needs_user_verification= semantics as a theoretical manhole-cover in to a world of cumbersome identity verification stages.

* A Minimal Authorized Agent

** User Identity Verification system

** User Agent

*** API Keys and Security Considerations

** Generating Identity Tokens

** Status Tracking

** Batching Backend

** OIDC client -- fetching JWT identity tokens from covered business identity provider

* A Minimal Privacy Infrastructure Provider

DRP doesn't aim to define the shape of the Privacy Infrastructure Provider's product. It could be a CSV download of DSRs and an SFTP upload, or it could be a full cloud automation suite, or it could send emails to paralegals. Be innovative!

the Covered Business is the one who is ultimately operating a product the PIP is responsible for.

a covered business can implement DRP on their own and work to be included in the DRP implementer's group.

** HTTP API

*** Implement =/exercise=

Store the inbound request in the data store, notify the covered business, plug request in to existing Data Subject Management product solution.

*** Implement =/revoke=

end users have the ability to revoke or cancel a request that is in an non-terminal state. Plug this in to your existing workflow engine

*** Implement Authorzied Agent status callback

Authorized agents are encouraged to run a web server which is capable of being POST'd a Data Rights Status JSON object, and PIPs are encouraged to notify one if a Data Rights Request includes a =status_callback= key.

*** Implement =/status= 

Backend-less authorized agents request the status of a DSR using this API to refresh the user agent. This status is described in the specification section 3.02.

*** Probably some =need_user_verification= product

A covered business may want to bring their own account verification system, but a PIP could integrate a form-builder in to their product and manage the =user_verification_url=.

** Workflow Management

*** The PIP "owns" the status of the request

a covered business is basically moving the data request through a "unacknowledged → verifying → in-progress → end state" workflow

*** What information does the covered business have access to?

- information about the authorized agent (provided out of band, extracted from JWT iss as that is signed)
- identity attributes (there is a level of assurance/trust that has to be assured out of band. 🤞 for eKYC), ✌verified✌ attributes in the meantime
- important dates (45 days after ack for CCPA)
- 

*** What actions can a CB be expected to take?

- update a request's state with information about the status of a request in progress
- request information or verification by providing a URL
- a covered business could be running an OIDC server they want consumers to authenticate against
- in theory there may be ways for the Covered Business to trust a token generated by popular third-party OIDC providers, provided by the AA?
- 
  
*** Status Tracking
