@startuml
title DRP Request Flow

Actor User
participant "Authorized Agent" 
participant "DRP Network"
participant "Privacy Infrastructure" 
participant "Covered Business"

note right of User
        dashed sequence lines are out of scope
        of DRP, specific to implementation of
        AA, PIP, resepectively
end note


== Background Sync between DRP Directories and Participants ==
note over "Privacy Infrastructure", "Authorized Agent"
        This has not been added to spec yet. for discussion
        see [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/issues/60]] 
end note
"Authorized Agent" -> "DRP Network": fetch businesses' API/etc\nfrom directory
"Privacy Infrastructure" -> "DRP Network": fetch agents' signing keys, etc\nfrom directory

== Onboarding and request creation ==

User --> "Authorized Agent": Onboard and verify\nidentity attributes once
User --> "Authorized Agent": Requests data rights action to\nspecific business

opt "AA has not interacted with this PIP before"
        note over "Privacy Infrastructure", "Authorized Agent"
                (This sequence/endpoint has not been added to spec yet,
                [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/issues/58]] for discussion)
        end note
        "Authorized Agent" -> "Privacy Infrastructure": fetch API token w/ signed request\nif this relationship is new
        "Privacy Infrastructure" -> "Authorized Agent": Provide an API token which can be used to authenticate GET requests,\nprovide rate limiting on agent by agent basis, etc
end

== Request State Machine ==

"Authorized Agent" -> "Privacy Infrastructure": construct a Data Rights Request and submits to API backend [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/0863d03717082599e19930ea6f009c048b86e979/data-rights-protocol.md#202-post-exercisekidaa-id-data-rights-exercise-endpoint POST /exercise]]

"Privacy Infrastructure" --> "Privacy Infrastructure": Verify signature of request, etc\npersist request
"Privacy Infrastructure" -> "Authorized Agent": return request ID [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/0863d03717082599e19930ea6f009c048b86e979/data-rights-protocol.md#user-content-303-schema-status-of-a-data-subject-exercise-request response schema]]
note over "Privacy Infrastructure", "Authorized Agent" 
        [POST /exercise response, [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/0863d03717082599e19930ea6f009c048b86e979/data-rights-protocol.md#203-get-status-data-rights-status-endpoint GET /status]], [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/0863d03717082599e19930ea6f009c048b86e979/data-rights-protocol.md#user-content-204-post-status_callback-data-rights-status-callback-endpoint POST status_callback]]]
        request state: OPEN
end note

"Privacy Infrastructure" --> "Covered Business": process is out of scope for protocol,\nsuggest integrating directly to existing DSR tooling
activate "Covered Business"
        "Covered Business" --> "Covered Business": process request through normal DSR process\nverify identity, collect records, process\nrequest using PIP tooling
        "Privacy Infrastructure" -> "Authorized Agent": Inform Agent request is acknowledged [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/0863d03717082599e19930ea6f009c048b86e979/data-rights-protocol.md#user-content-303-schema-status-of-a-data-subject-exercise-request schema]]
        note over "Privacy Infrastructure", "Authorized Agent" 
                request state: IN PROGRESS
        end note

        opt "optional additional verification flow [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/0863d03717082599e19930ea6f009c048b86e979/data-rights-protocol.md#3021-need_user_verification-state-flow-semantics (DRP 3.02.1)]]"
                "Covered Business" --> "Privacy Infrastructure": need additional verification of consumer identity\ndirect user to visit a specific URL.
                "Privacy Infrastructure" -> "Authorized Agent": Update request state to need_user_verification
                note over "Privacy Infrastructure", "Authorized Agent" 
                        request state: IN PROGRESS
                        needs_user_verification
                end note
                
                "Authorized Agent" --> User: Notify user of requirement
                User -> "Covered Business": User visits URL in browser or webview and provides verification
                alt "identity verification successful?"
                        "Covered Business" --> "Privacy Infrastructure": verification complete
                        "Privacy Infrastructure" -> "Authorized Agent": move request forward in state machine
                        note over "Privacy Infrastructure", "Authorized Agent" 
                                request state: IN PROGRESS
                        end note
                else
                        "Covered Business" --> "Privacy Infrastructure": Signal to close request
                        "Privacy Infrastructure" ->x "Authorized Agent": Signal to close request
                        note over "Privacy Infrastructure", "Authorized Agent" 
                                request state: DENIED
                                request sequence terminates
                                a request can be denied for a number of [[https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/0863d03717082599e19930ea6f009c048b86e979/data-rights-protocol.md#302-request-statuses different reasons]]
                        end note
                end
        end

        "Covered Business" --> "Covered Business": Process Request....
        "Covered Business" --> "Privacy Infrastructure": Processing is completed
deactivate "Covered Business"
"Privacy Infrastructure" -> "Authorized Agent": update request state, callback to Authorized Agent
note over "Privacy Infrastructure", "Authorized Agent" 
        request state: FULFILLED
end note

"Authorized Agent" --> User: Notify user of completion
User -> "Covered Business": User may have results URL to download or view in browser or user agent
@enduml
